<head>
    <!--START: Facebook OG tags-->
    <meta property="og:url" content="<?php echo $this->escape($this->article_url)?>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?php echo $this->escape($this->title)?>" />
    <meta property="og:description" content="<?php echo $this->escape($this->description)?>" />
    <meta property="og:image" content="<?php echo $this->escape($this->image)?>" />
    <!--END: Facebook OG tags-->
</head>
<body>
    <br>
    Title: <?php echo $this->escape($this->title)?>
    <br>
    Publishing date: <?php echo $this->escape($this->date)?>
    <br>
    Description: <?php echo $this->escape($this->description)?>
    <br>
    Article body:
    <br>
    <?php echo $this->body?>
    <br>
    Article social HTML:
    <br>
    <?php echo $this->social?>
    <br>
    Image preview link: <?php echo $this->escape($this->image)?>
    <br>
</body>