<head>
    <link rel='stylesheet' href='/resources/style.css' />
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <link rel="shortcut icon" href="/images/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/images/favicon/favicon.ico" type="image/x-icon">
    <title>404 - FastBlog</title>
</head>
<body>
<div class="graybar">
    <div class="center950px">
        <div class="fastblog">Fast<font color="#fff">Blog</font></div><br>
        <div class="horizontal-menu">
            <ul>
                <li><a href="/index"><i class="icon fas fa-info"></i>Introduction</a></li>
                <li><a href="/installation"><i class="icon fas fa-cog"></i>Basic Installation</a></li>
                <li><a href="/users"><i class="icon fas fa-file-alt"></i>Article Example</a></li>
                <li><a href="/latest"><i class="icon fas fa-copy"></i>Latest articles</a></li>
                <li style="float:right"><a href="https://github.com/HexelDev/FastBlog" ><i class="icon fab fa-github"></i>GitHub</a></li>
                <li style="float:right"><a href="/admin"><i class="icon fas fa-sliders-h"></i>Admin Control Panel</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="center950px">
    <div class="error">
        <div class="code">We can't find what you where searching for...</div>
        <div class="description"><br>Error 404: Resource not found</div>
    </div>
</div>
</div>
<div class="graybar footer" style="height: 50px; float:bottom;">
    <div class="center950px">
        <div style="float:left; width:50%; display:block; line-height:50px;">
            FastBlog v0.1
        </div>
        <div style="float:left; width:50%; display:block; text-align:right;line-height:50px;">
            Made with <i class="fas fa-heart"></i> by Hexel
        </div>
    </div>
</div>
</body>