<head>
    <link rel='stylesheet' href='/resources/style.css' />
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <link rel="shortcut icon" href="/images/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/images/favicon/favicon.ico" type="image/x-icon">
    <title>Introduction - FastBlog</title>
</head>
<body>
<div class="graybar">
    <div class="center950px">
        <div class="fastblog">Fast<font color="#fff">Blog</font></div><br>
        <div class="horizontal-menu">
            <ul>
                <li><a class="active" href="/index"><i class="icon fas fa-info"></i>Introduction</a></li>
                <li><a href="/installation"><i class="icon fas fa-cog"></i>Basic Installation</a></li>
                <li><a href="/users"><i class="icon fas fa-file-alt"></i>Article Example</a></li>
                <li><a href="/latest"><i class="icon fas fa-copy"></i>Latest articles</a></li>
                <li style="float:right"><a href="https://github.com/HexelDev/FastBlog" ><i class="icon fab fa-github"></i>GitHub</a></li>
                <li style="float:right"><a href="/admin"><i class="icon fas fa-sliders-h"></i>Admin Control Panel</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="center950px">
    <div class="cont-50">
        <div class="header">
            <i class="fas fa-info"></i> Project idea
        </div>
        <div class="content">
            I have been looking for a blog CMS _(content manage system)_ that simplified
            only the management process, but I haven’t found anything similar. That's why <b>I decided to create my own CMS built for
            developer end-users</b>, giving 'em a real free hand over a simple and clean system without useless functions.
        </div>
        <div class="header">
            <i class="fas fa-cloud-download-alt"></i> Dependecies
        </div>
        <div class="content">
            This project requires third-party dependencies managed by <b>Composer</b>, a Dependency Manager for PHP.<br>
            <ul>
                <li><b>Klein.php:</b> is a fast & flexible router for PHP 5.3+ (<a href="https://github.com/klein/klein.php">GitHub</a>) (MIT)</li>

                <li><b>Idiorm:</b> a lightweight nearly-zero-configuration object-relational mapper and fluent query builder for PHP5. (<a href="https://github.com/j4mie/idiorm">GitHub</a>) (BSD)</li>
            </ul>
            Also FastBlog uses some cool project through theirs CDN (Content Delivery Network).
            <ul>
                <li><b>Font Awesome:</b> The internet's most popular icon toolkit (<a href="https://github.com/FortAwesome/Font-Awesome">GitHub</a>)</li>

                <li><b>QuillJs:</b> QuillJS is a modern rich text editor built for compatibility and extensibility (<a href="https://github.com/quilljs/quill">GitHub</a>)</li>

                <li><b>jQuery:</b> jQuery is a fast, small, and feature-rich JavaScript library (<a href="https://github.com/jquery/jquery">GitHub</a>)</li>
            </ul>
        </div>
    </div>
    <div class="cont-50">
        <div class="header">
            <i class="fas fa-info"></i> Installation
        </div>
        <div class="content">
            <ul>
                <li><b>Nginx: </b> Create a Nginx conf and unzip the CMS inside the prefered directory
                    <div class="p2">Tutorial: <a href="">GitHub wiki page</a>
                </li>
            </ul>
            <ul>
                <li><b>Apache: </b> Unzip the CMS inside your webspace
                    <div class="p2">Tutorial: <a href="">GitHub wiki page</a>
                </li>
            </ul>
        </div>
        <div class="header">
            <i class="far fa-copyright"></i> License
        </div>
        <div class="content">
			<pre><code>
BSD 3-Clause License

Copyright (c) 2018, HexelDev
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
			</code></pre>
        </div>
    </div>
</div>
<div class="graybar footer" style="height: 50px; float:bottom;">
    <div class="center950px">
        <div style="float:left; width:50%; display:block; line-height:50px;">
            FastBlog v0.1
        </div>
        <div style="float:left; width:50%; display:block; text-align:right;line-height:50px;">
            Made with <i class="fas fa-heart"></i> by Hexel
        </div>
    </div>
</div>
</body>
